name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clone dependencies repository
      run: |
        git clone https://github.com/OpenClassrooms-Student-Center/JavaPathENProject8.git TourGuide

    - name: Build gpsUtil TourGuide
      run: |
        cd TourGuide/libs/gpsUtil
        mvn install

    - name: Build tripPricer TourGuide
      run: |
        cd TourGuide/libs/tripPricer
        mvn install

    - name: Build rewardCentral TourGuide
      run: |
        cd TourGuide/libs/rewardCentral
        mvn install

    - name: Compile project
      run: |
        mvn compile

    - name: Run all tests (including performance tests)
      run: |
        mvn test

    - name: Build artifact
      run: |
        mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
