name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        

    - name: Build gpsUtil dependency
        cd TourGuide/libs/gpsUtil
      run: mvn install
    

    - name: Build tripPricer dependency
         cd TourGuide/libs/tripPricer
      run: mvn install 

    - name: Build rewardCentral dependency
        cd TourGuide/libs/rewardCentral
      run: mvn install

    - name: Compile project
       cd TourGuide
      run: mvn compile

    - name: Run all tests (including performance tests)
        cd TourGuide
      run: mvn test

    - name: Build artifact
       cd TourGuide
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
