name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'


    - name: Compile project
      run: |
        cd TourGuide
        mvn compile

    - name: Run all tests (including performance tests)
      run: |
        cd TourGuide
        mvn test

    - name: Build artifact
      run: |
        cd TourGuide
        mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: TourGuide/target/*.jar
