name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci-tests:
    name: Tests unitaires (hors performance)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile project
        run: |
          cd TourGuide
          mvn compile

      - name: Run unit tests (excluding performance)
        run: |
          cd TourGuide
          mvn test -Dtest='*TestTourGuideService' -DexcludeTests='TestTourGuideService#highVolumeTrackLocation+TestTourGuideService#highVolumeGetRewards'

      - name: Build artifact
        run: |
          cd TourGuide
          mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-artifact
          path: TourGuide/target/*.jar

  performance-track:
    name: Performance Test - highVolumeTrackLocation
    runs-on: ubuntu-latest
    needs: ci-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run highVolumeTrackLocation with 5000 users
        run: |
          cd TourGuide
          mvn test -Dtest=TestTourGuideService#highVolumeTrackLocation -Duser.count=5000

  performance-rewards:
    name: Performance Test - highVolumeGetRewards
    runs-on: ubuntu-latest
    needs: ci-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run highVolumeGetRewards with 7500 users
        run: |
          cd TourGuide
          mvn test -Dtest=TestTourGuideService#highVolumeGetRewards -Duser.count=7500
