name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clone dependencies repository
      run: |
        git clone https://github.com/OpenClassrooms-Student-Center/JavaPathENProject8.git dependencies

    - name: Build gpsUtil dependency
      run: |
        cd libs/gpsUtil
        mvn install

    - name: Build tripPricer dependency
      run: |
        cd libs/tripPricer
        mvn install

    - name: Build rewardCentral dependency
      run: |
        cd libs/rewardCentral
        mvn install

    - name: Compile project
       cd TourGuide
      run: mvn compile

    - name: Run all tests (including performance tests)
        cd TourGuide
      run: mvn test

    - name: Build artifact
       cd TourGuide
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
