name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clone dependencies repository
      run: |
        git clone https://github.com/OpenClassrooms-Student-Center/JavaPathENProject8.git dependencies

    - name: Check folder structure
      run: |
        ls -R dependencies

    # Commenter temporairement les étapes suivantes jusqu'à ce qu'on valide les chemins corrects
    # - name: Build gpsUtil dependency
    #   run: |
    #     cd dependencies/libs/gpsUtil
    #     mvn install
