name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build gpsUtil dependency
      run: |
        rm -rf gpsUtil
        git clone https://github.com/Z093/TourGuide.git gpsUtil
        cd gpsUtil
        mvn install

    - name: Build tripPricer dependency
      run: |
        rm -rf tripPricer
        git clone https://github.com/Z093/TourGuide.git tripPricer
        cd tripPricer
        mvn install

    - name: Build rewardCentral dependency
      run: |
        rm -rf rewardCentral
        git clone https://github.com/Z093/TourGuide.git rewardCentral
        cd rewardCentral
        mvn install

    - name: Compile project
      run: cd TourGuide && mvn compile

    - name: Run all tests (including performance tests)
      run: cd TourGuide && mvn test

    - name: Build artifact
      run: cd TourGuide && mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: app/target/*.jar
